/**
 * Shared Kerala location data for GramConnect.
 * Used by both Registration, Report Issue, and Announcement targeting dropdowns.
 */

export const KERALA_DISTRICTS = [
  'Thiruvananthapuram',
  'Kollam',
  'Pathanamthitta',
  'Alappuzha',
  'Kottayam',
  'Idukki',
  'Ernakulam',
  'Thrissur',
  'Palakkad',
  'Malappuram',
  'Kozhikode',
  'Wayanad',
  'Kannur',
  'Kasaragod'
];

/**
 * Kerala district → panchayats/local bodies mapping.
 * Each district maps to a flat sorted list of its panchayats/municipalities/corporations.
 */
export const DISTRICT_PANCHAYATS = {
  Thiruvananthapuram: [
    'Thiruvananthapuram Corporation',
    'Vattiyoorkavu Panchayat',
    'Kazhakkoottam Panchayat',
    'Neyyattinkara Municipality',
    'Balaramapuram Panchayat',
    'Parassala Panchayat',
    'Nedumangad Municipality',
    'Aruvikkara Panchayat',
    'Vellanad Panchayat',
    'Attingal Municipality',
    'Chirayinkeezhu Panchayat',
    'Kadakkavoor Panchayat',
    'Varkala Municipality',
    'Edava Panchayat',
    'Elakamon Panchayat',
    'Kattakada Panchayat',
    'Malayinkeezhu Panchayat',
    'Maranalloor Panchayat'
  ],
  Kollam: [
    'Kollam Corporation',
    'Eravipuram Panchayat',
    'Chathannoor Panchayat',
    'Karunagappally Municipality',
    'Oachira Panchayat',
    'Clappana Panchayat',
    'Sasthamcotta Panchayat',
    'Sooranad Panchayat',
    'Kunnathur Panchayat',
    'Pathanapuram Panchayat',
    'Piravanthoor Panchayat',
    'Vilakkudy Panchayat',
    'Punalur Municipality',
    'Anchal Panchayat',
    'Yerur Panchayat',
    'Kottarakkara Municipality',
    'Veliyam Panchayat',
    'Ummannur Panchayat'
  ],
  Pathanamthitta: [
    'Adoor Municipality',
    'Pandalam Municipality',
    'Kadampanad Panchayat',
    'Konni Panchayat',
    'Pramadom Panchayat',
    'Kalanjoor Panchayat',
    'Pathanamthitta Municipality',
    'Aranmula Panchayat',
    'Kozhencherry Panchayat',
    'Ranni Panchayat',
    'Vadasserikkara Panchayat',
    'Angadi Panchayat',
    'Mallappally Panchayat',
    'Anicadu Panchayat',
    'Kottanadu Panchayat',
    'Thiruvalla Municipality',
    'Koipuram Panchayat',
    'Kaviyoor Panchayat'
  ],
  Alappuzha: [
    'Alappuzha Municipality',
    'Ambalappuzha Panchayat',
    'Punnapra Panchayat',
    'Chengannur Municipality',
    'Mannar Panchayat',
    'Budhanoor Panchayat',
    'Mavelikkara Municipality',
    'Chennithala Panchayat',
    'Vallikunnam Panchayat',
    'Kayamkulam Municipality',
    'Haripad Municipality',
    'Karthikappally Panchayat',
    'Pulincunnoo Panchayat',
    'Nedumudi Panchayat',
    'Champakulam Panchayat',
    'Cherthala Municipality',
    'Aroor Panchayat',
    'Pattanakkad Panchayat'
  ],
  Kottayam: [
    'Changanasserry Municipality',
    'Kurichy Panchayat',
    'Madappally Panchayat',
    'Kottayam Municipality',
    'Ettumanoor Municipality',
    'Vijayapuram Panchayat',
    'Vaikom Municipality',
    'Thalayolaparambu Panchayat',
    'Kaduthuruthy Panchayat',
    'Pala Municipality',
    'Erattupetta Municipality',
    'Bharananganam Panchayat',
    'Kanjirappally Panchayat',
    'Erumely Panchayat',
    'Mundakayam Panchayat'
  ],
  Idukki: [
    'Peermade Panchayat',
    'Vandiperiyar Panchayat',
    'Kumily Panchayat',
    'Kattappana Municipality',
    'Nedumkandam Panchayat',
    'Udumbanchola Panchayat',
    'Munnar Panchayat',
    'Devikulam Panchayat',
    'Marayoor Panchayat',
    'Thodupuzha Municipality',
    'Muttom Panchayat',
    'Karimannoor Panchayat',
    'Vazhathope Panchayat',
    'Kanjikuzhy Panchayat',
    'Mariapuram Panchayat'
  ],
  Ernakulam: [
    'Kochi Corporation',
    'Tripunithura Municipality',
    'Kalamassery Municipality',
    'Aluva Municipality',
    'Angamaly Municipality',
    'Nedumbassery Panchayat',
    'Perumbavoor Municipality',
    'Kunnathunad Panchayat',
    'Pattimattom Panchayat',
    'Muvattupuzha Municipality',
    'Piravom Municipality',
    'Valakom Panchayat',
    'Kothamangalam Municipality',
    'Varappetty Panchayat',
    'Pindimana Panchayat',
    'North Paravur Municipality',
    'Eloor Municipality',
    'Varapuzha Panchayat',
    'Chellanam Panchayat',
    'Kumbalangi Panchayat'
  ],
  Thrissur: [
    'Thrissur Corporation',
    'Ollur Panchayat',
    'Amballur Panchayat',
    'Chalakkudy Municipality',
    'Athirappilly Panchayat',
    'Kodakara Panchayat',
    'Irinjalakuda Municipality',
    'Pudukkad Panchayat',
    'Aloor Panchayat',
    'Kodungallur Municipality',
    'Mathilakam Panchayat',
    'Eriyad Panchayat',
    'Chavakkad Municipality',
    'Guruvayur Municipality',
    'Vadakkekad Panchayat',
    'Kunnamkulam Municipality',
    'Porkulam Panchayat',
    'Choondal Panchayat',
    'Wadakkanchery Municipality',
    'Chelakkara Panchayat',
    'Pazhayannur Panchayat'
  ],
  Palakkad: [
    'Palakkad Municipality',
    'Malampuzha Panchayat',
    'Elappully Panchayat',
    'Alathur Panchayat',
    'Kuzhalmannam Panchayat',
    'Tarur Panchayat',
    'Chittur-Thathamangalam Municipality',
    'Nelliampathy Panchayat',
    'Kozhinjampara Panchayat',
    'Mannarkkad Municipality',
    'Attappady Panchayat',
    'Alanallur Panchayat',
    'Ottappalam Municipality',
    'Shoranur Municipality',
    'Cherpulassery Municipality',
    'Pattambi Municipality',
    'Koppam Panchayat',
    'Thrithala Panchayat'
  ],
  Malappuram: [
    'Nilambur Municipality',
    'Edakkara Panchayat',
    'Vazhikkadavu Panchayat',
    'Manjeri Municipality',
    'Areacode Panchayat',
    'Edavanna Panchayat',
    'Kondotty Municipality',
    'Nediyiruppu Panchayat',
    'Pulikkal Panchayat',
    'Tirurangadi Municipality',
    'Parappanangadi Municipality',
    'Chelari Panchayat',
    'Tirur Municipality',
    'Tanur Municipality',
    'Valanchery Municipality',
    'Ponnani Municipality',
    'Edappal Panchayat',
    'Tavanur Panchayat',
    'Perinthalmanna Municipality',
    'Kottakkal Municipality',
    'Angadipuram Panchayat'
  ],
  Kozhikode: [
    'Kozhikode Corporation',
    'Ramanattukara Municipality',
    'Feroke Municipality',
    'Vadakara Municipality',
    'Chorode Panchayat',
    'Onchiyam Panchayat',
    'Koyilandy Municipality',
    'Payyoli Municipality',
    'Atholi Panchayat',
    'Thamarassery Panchayat',
    'Koduvally Municipality',
    'Thiruvambady Panchayat'
  ],
  Wayanad: [
    'Mananthavady Municipality',
    'Thirunelly Panchayat',
    'Vellamunda Panchayat',
    'Sulthan Bathery Municipality',
    'Ambalavayal Panchayat',
    'Noolpuzha Panchayat',
    'Kalpetta Municipality',
    'Vythiri Panchayat',
    'Meppadi Panchayat'
  ],
  Kannur: [
    'Kannur Corporation',
    'Pappinisseri Panchayat',
    'Valapattanam Panchayat',
    'Payyannur Municipality',
    'Cherupuzha Panchayat',
    'Karivellur Panchayat',
    'Taliparamba Municipality',
    'Alakode Panchayat',
    'Sreekandapuram Municipality',
    'Thalassery Municipality',
    'Mattannur Municipality',
    'Kuthuparamba Municipality',
    'Iritty Municipality',
    'Peravoor Panchayat',
    'Ulikkal Panchayat'
  ],
  Kasaragod: [
    'Kasaragod Municipality',
    'Badiadka Panchayat',
    'Mogral Puthur Panchayat',
    'Kanhangad Municipality',
    'Nileshwaram Municipality',
    'Cheruvathur Panchayat',
    'Manjeshwar Panchayat',
    'Uppala Panchayat',
    'Kumbla Panchayat',
    'Vellarikundu Panchayat',
    'West Eleri Panchayat',
    'Balal Panchayat'
  ]
};

/**
 * Returns the sorted list of panchayats/local-bodies for a given district name.
 * Returns empty array if district is 'All Districts' or not found.
 * @param {string} district 
 * @returns {string[]}
 */
export const getPanchayatsForDistrict = (district) => {
  if (!district || district === 'All Districts' || district === 'All') return [];
  return DISTRICT_PANCHAYATS[district] || [];
};
